plugins/nopCommerce/Nop.Plugin.Payments.RaboOmniKassa/Controllers/PaymentRaboOmniKassaController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Extensions.Primitives;
using Nop.Core;
using Nop.Core.Domain.Orders;
using Nop.Plugin.Payments.RaboOmniKassa.Models;
using Nop.Plugin.Payments.RaboOmniKassa.Services;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Orders;
using Nop.Services.Security;
using Nop.Services.Stores;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;
using OmniKassa.Exceptions;
using OmniKassa.Model.Response;
using OmniKassa.Model.Response.Notification;

namespace Nop.Plugin.Payments.RaboOmniKassa.Controllers
{
    public class PaymentRaboOmniKassaController : BasePaymentController
    {
        #region Fields

        private readonly ILogger _logger;
        private readonly IWorkContext _workContext;
        private readonly IStoreService _storeService;
        private readonly ISettingService _settingService;
        private readonly IPermissionService _permissionService;
        private readonly IOrderService _orderService;
        private readonly IOrderProcessingService _orderProcessingService;
        private readonly ILocalizationService _localizationService;
        private readonly RaboOmniKassaPaymentManager _raboOmniKassaPaymentManager;
        private readonly RaboOmniKassaPaymentSettings _raboOmniKassaPaymentSettings;

        #endregion Fields

        #region Constructor

        /// <summary>
        /// Constructor.
        /// </summary>
        public PaymentRaboOmniKassaController(
            ILogger logger,
            IWorkContext workContext,
            IStoreService storeService, 
            ISettingService settingService,
            IPermissionService permissionService,
            IOrderService orderService,
            IOrderProcessingService orderProcessingService,
            ILocalizationService localizationService,
            RaboOmniKassaPaymentManager raboOmniKassaPaymentManager,
            RaboOmniKassaPaymentSettings raboOmniKassaPaymentSettings)
        {
            _logger = logger;
            _workContext = workContext;
            _storeService = storeService;
            _settingService = settingService;
            _permissionService = permissionService;
            _orderService = orderService;
            _orderProcessingService = orderProcessingService;
            _localizationService = localizationService;
            _raboOmniKassaPaymentManager = raboOmniKassaPaymentManager;
            _raboOmniKassaPaymentSettings = raboOmniKassaPaymentSettings;
        }

        #endregion Contructor

        #region Utilities

        private Dictionary<String, String> GetDictionary(Dictionary<String, StringValues> collection)
        {
            var dictionary = new Dictionary<String, String>();
            foreach (var pair in collection)
            {
                dictionary.Add(pair.Key, pair.Value);
            }

            return dictionary;
        }

        #endregion Utilities

        #region Methods

        [AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        public IActionResult Configure()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();
            
            // Load settings for a chosen store scope.
            var storeScope = this.GetActiveStoreScopeConfiguration(_storeService, _workContext);
            var raboOmniKassaPaymentSettings = _settingService.LoadSetting<RaboOmniKassaPaymentSettings>(storeScope);

            var model = new ConfigurationModel
            {
                UseSandbox = raboOmniKassaPaymentSettings.UseSandbox,
                SigningKey = raboOmniKassaPaymentSettings.SigningKey,
                RefreshToken = raboOmniKassaPaymentSettings.RefreshToken,
                AdditionalFee = raboOmniKassaPaymentSettings.AdditionalFee,
                AdditionalFeePercentage = raboOmniKassaPaymentSettings.AdditionalFeePercentage,
                ActiveStoreScopeConfiguration = storeScope
            };

            if (storeScope > 0)
            {
                model.UseSandbox_OverrideForStore = _settingService.SettingExists(raboOmniKassaPaymentSettings, x => x.UseSandbox, storeScope);
                model.SigningKey_OverrideForStore = _settingService.SettingExists(raboOmniKassaPaymentSettings, x => x.SigningKey, storeScope);
                model.RefreshToken_OverrideForStore = _settingService.SettingExists(raboOmniKassaPaymentSettings, x => x.RefreshToken, storeScope);
                model.AdditionalFee_OverrideForStore = _settingService.SettingExists(raboOmniKassaPaymentSettings, x => x.AdditionalFee, storeScope);
                model.AdditionalFeePercentage_OverrideForStore = _settingService.SettingExists(raboOmniKassaPaymentSettings, x => x.AdditionalFeePercentage, storeScope);
            }

            return View("~/Plugins/Payments.RaboOmniKassa/Views/Configure.cshtml", model);
        }

        [HttpPost]
        [AuthorizeAdmin]
        [AdminAntiForgery]
        [Area(AreaNames.Admin)]
        public IActionResult Configure(ConfigurationModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            if (!ModelState.IsValid)
                return Configure();

            // Load settings for a chosen store scope.
            var storeScope = this.GetActiveStoreScopeConfiguration(_storeService, _workContext);
            var raboOmniKassaPaymentSettings = _settingService.LoadSetting<RaboOmniKassaPaymentSettings>(storeScope);

            // Save settings.
            raboOmniKassaPaymentSettings.UseSandbox = model.UseSandbox;
            raboOmniKassaPaymentSettings.SigningKey = model.SigningKey;
            raboOmniKassaPaymentSettings.RefreshToken = model.RefreshToken;
            raboOmniKassaPaymentSettings.AdditionalFee = model.AdditionalFee;
            raboOmniKassaPaymentSettings.AdditionalFeePercentage = model.AdditionalFeePercentage;

            // We do not clear cache after each setting update.
            // This behavior can increase performance because cached settings will 
            // not be cleared and loaded from database after each update.
            _settingService.SaveSettingOverridablePerStore(raboOmniKassaPaymentSettings, x => x.UseSandbox, model.UseSandbox_OverrideForStore, storeScope, false);
            _settingService.SaveSettingOverridablePerStore(raboOmniKassaPaymentSettings, x => x.SigningKey, model.SigningKey_OverrideForStore, storeScope, false);
            _settingService.SaveSettingOverridablePerStore(raboOmniKassaPaymentSettings, x => x.RefreshToken, model.RefreshToken_OverrideForStore, storeScope, false);
            _settingService.SaveSettingOverridablePerStore(raboOmniKassaPaymentSettings, x => x.AdditionalFee, model.AdditionalFee_OverrideForStore, storeScope, false);
            _settingService.SaveSettingOverridablePerStore(raboOmniKassaPaymentSettings, x => x.AdditionalFeePercentage, model.AdditionalFeePercentage_OverrideForStore, storeScope, false);

            // Now clear the settings cache.
            _settingService.ClearCache();

            SuccessNotification(_localizationService.GetResource("Admin.Plugins.Saved"));

            return Configure();
        }

        [HttpPost]
        public IActionResult WebhookEventHandler([FromBody] ApiNotification notification)
        {
            try
            {
                _logger.Information("OmniKassa Webhook called: PoiId=" + notification.PoiId + ", EventName="  + notification.EventName + ", Expiry=" + notification.Expiry);

                MerchantOrderStatusResponse response = null;
                
                do
                {
                    response = _raboOmniKassaPaymentManager.GetOrderStatusData(notification);

                    foreach (var result in response.OrderResults)
                    {
                        _logger.Information("OmniKassa order update: " +
                                "MerchantOrderId=" + result.MerchantOrderId +
                                ", OmnikassaOrderId=" + result.OmnikassaOrderId +
                                ", OrderStatus=" + result.OrderStatus.ToString() +
                                ", Amount=" + result.TotalAmount.Amount.ToString() +
                                ", ErrorCode=" + result.ErrorCode);

                        var order = _orderService.GetOrderById(Convert.ToInt32(result.MerchantOrderId));
                        bool success = HandleOrderStatus(order, result.OrderStatus);
                        if(!success)
                        {
                            _logger.Error($"OmniKassa error: Order with id {result.MerchantOrderId} was not found");
                        }
                    }

                }
                while (response.MoreOrderResultsAvailable);
            }

            catch (RabobankSdkException ex)
            {
                _logger.Error(ex.InnerException != null ? ex.InnerException.Message : ex.Message);
            }

            // Nothing should be rendered to visitor
            return Content("");
        }

        /// <summary>
        /// Handler for the Merchant Return Url (specified when announcing an order).
        /// </summary>
        [HttpGet]
        public IActionResult ReturnUrlEventHandler()
        {
            try
            {
                Dictionary<String, StringValues> query = QueryHelpers.ParseQuery(Request.QueryString.Value);
                Dictionary<String, String> dictionary = GetDictionary(query);

                // Parse the response and check if the signature is valid (an exception will be thrown if this is not the case).

plugins/nopCommerce/Nop.Plugin.Payments.RaboOmniKassa/Views/Configure.cshtml
@model Nop.Plugin.Payments.RaboOmniKassa.Models.ConfigurationModel
@{
    Layout = "_ConfigurePlugin";
}
@inject Nop.Core.IWebHelper _webHelper

@await Component.InvokeAsync("StoreScopeConfiguration")

<form asp-controller="PaymentRaboOmniKassa" asp-action="Configure" method="post">
    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-body">
                @Html.Raw(string.Format(T("Plugins.Payments.RaboOmniKassa.Instructions").Text, $"{_webHelper.GetStoreLocation(true)}Plugins/PaymentRaboOmniKassa/Webhook"))

                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="UseSandbox_OverrideForStore" asp-input="UseSandbox" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="UseSandbox" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="UseSandbox" />
                        <span asp-validation-for="UseSandbox"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="SigningKey_OverrideForStore" asp-input="SigningKey" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="SigningKey" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="SigningKey" />
                        <span asp-validation-for="SigningKey"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="RefreshToken_OverrideForStore" asp-input="RefreshToken" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="RefreshToken" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="RefreshToken" />
                        <span asp-validation-for="RefreshToken"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="AdditionalFee_OverrideForStore" asp-input="AdditionalFee" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="AdditionalFee" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="AdditionalFee" />
                        <span asp-validation-for="AdditionalFee"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="AdditionalFeePercentage_OverrideForStore" asp-input="AdditionalFeePercentage" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="AdditionalFeePercentage" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="AdditionalFeePercentage" />
                        <span asp-validation-for="AdditionalFeePercentage"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-9 col-md-offset-3">
                        <input type="submit" name="save" class="btn btn-primary" value="@T("Admin.Common.Save")" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

plugins/nopCommerce/Nop.Plugin.Payments.RaboOmniKassa/Views/PaymentInfo.cshtml
@{
    Layout = "";
}
<table width="100%" cellpadding="0" cellspacing="0">
    <tr>
        <td>
            <p><b>@T("Plugins.Payments.RaboOmniKassa.Fields.RedirectionTip")</b></p>
        </td>
    </tr>
</table>